name: w3r

services:
  bitcoin:
    image: lncm/bitcoind:v28.0
    user: 1000:1000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${BITCOIN_STORAGE}:/data/.bitcoin # data in /bitcoin/.bitcoin
    restart: unless-stopped
    stop_grace_period: 15m30s
    ports: 
      - "8333:8333"
      - "8332:8332"
      - "28332:28332"
      - "28333:28333"
    command: >
      -disablewallet
      -server -rest -rpcuser=${BITCOIN_RPC_USER} -rpcpassword=${BITCOIN_RPC_PASSWORD} -rpcbind=0.0.0.0:8332 -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -rpcthreads=256
      -dbcache=16384
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -txindex=1 
      -coinstatsindex=1

  electrs:
    image: mempool/electrs:latest
    restart: unless-stopped
    depends_on:
      - bitcoin
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: >
      --network mainnet
      --daemon-dir /data/.bitcoin
      --db-dir /data/electrs
      --daemon-rpc-addr bitcoin:8332
      --electrum-rpc-addr 0.0.0.0:50001
      --http-addr 0.0.0.0:3000
      --monitoring-addr 0.0.0.0:4224
      --cookie ${BITCOIN_RPC_USER}:${BITCOIN_RPC_PASSWORD}
      --address-search
      --index-unspendables
      --cors '*'
      -vv
    ports:
      - "50001:50001"
      - "3000:3000"
      - "4224:4224"
    volumes:
      - ${BITCOIN_STORAGE}:/data/.bitcoin:ro
      - ${ELECTRS_STORAGE:-./electrs}:/data/electrs
